/**
 * Find the Difference
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Return the letter that was added to t.
 *
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
  let sCounts = {};
  let tCounts = {};

  for (let char of s) {
      sCounts[char] = (sCounts[char] || 0) + 1;
  }
  for (let char of t) {
      tCounts[char] = (tCounts[char] || 0) + 1;
  }

  for (let char in tCounts) {
      if (tCounts[char] !== sCounts[char]) return char;
  }
};